apiVersion: v1
kind: ServiceAccount
metadata:
  name: afmongo
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      serviceAccountName: afmongo
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "cloud.google.com/gke-nodepool"
                    operator: In
                    values:
                      - "pool-1"
      containers:
      - name: python-app
        image: gcr.io/gcp-pov/af_mongodb:v0.3
        imagePullPolicy: Always
        env:
        - name: PROJECT
          value: "gcp-pov"
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: "1"
        - name: GOOGLE_CLOUD_PROJECT
          value: "gcp-pov"
        - name: GOOGLE_CLOUD_LOCATION
          value: "us-central1"
        ports:
        - containerPort: 8501
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "128Mi"
        #   limits:
        #     cpu: "500m"
        #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
  - port: 80
    targetPort: 8501
  type: LoadBalancer

